# Generated by Django 4.2.4 on 2023-09-08 13:54

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inivitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('passport', models.CharField(max_length=20)),
                ('expire_date', models.DateField()),
                ('image', models.ImageField(upload_to='media/profile/')),
                ('access_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('forum_type', models.ManyToManyField(to='forum.forum')),
                ('invitation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.inivitation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
