# Generated by Django 4.2.5 on 2023-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_inivitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inivitation',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
