# Generated by Django 4.2.5 on 2023-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_inivitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
