# Generated by Django 4.2.5 on 2023-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_access_id_alter_user_org_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inivitation',
            name='amount',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
