# Generated by Django 4.2.5 on 2023-09-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_contact_phone_number_contact_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
