# Generated by Django 4.2.5 on 2023-09-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_connect_title_en_connect_title_ru_connect_title_uz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
