# Generated by Django 4.2.5 on 2023-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
