# Generated by Django 4.2.5 on 2023-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='short_key',
            field=models.CharField(choices=[('GA', 'General Assambly'), ('IF', 'Investment Forum'), ('EF', 'Educational Forum')], default='GA'),
        ),
    ]
