# Generated by Django 4.2.5 on 2023-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_description_en_forum_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='day_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='day_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventtime',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventtime',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventtime',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='context_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='context_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='context_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumproject',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
