# Generated by Django 4.2.5 on 2023-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_description_en_forum_description_ru_and_more'),
        ('forum', '0002_forum_short_key'),
    ]

    operations = [
    ]
