# Generated by Django 4.2.5 on 2023-09-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_short_key'),
        ('forum', '0003_event_day_en_event_day_ru_event_day_uz_and_more'),
    ]

    operations = [
    ]
