# Generated by Django 4.2.5 on 2023-09-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_merge_20230909_1937'),
        ('forum', '0004_merge_20230909_1922'),
    ]

    operations = [
    ]
