# Generated by Django 4.2.5 on 2023-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_merge_20230909_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='short_key',
            field=models.CharField(choices=[('GA', 'General Assambly'), ('IF', 'Investment Forum'), ('EF', 'Educational Forum')], default='GA', max_length=255),
        ),
    ]
