# Generated by Django 4.2.5 on 2023-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_event_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forumproject',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forumproject',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
